In [5]:
# Use scikit-learn to train and evaluate a Decision Tree classifier.

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [6]:
x, y = load_iris(return_X_y=True)

In [7]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [11]:
x_train

array([[5.1, 2.5, 3. , 1.1],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.8, 5.1, 2.4],
       [5.1, 3.3, 1.7, 0.5],
       [5.5, 2.4, 3.7, 1. ],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [6.3, 2.5, 4.9, 1.5],
       [4.8, 3. , 1.4, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [5.5, 2.5, 4. , 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.5, 2.3, 1.3, 0.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.4, 3.2, 4.5, 1.5],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [6.9, 3.1, 5.1, 2.3],
       [4.8, 3. , 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [6.7, 3. , 5. , 1.7],
       [5. , 3.4, 1.6, 0.4],
       [6. , 3. , 4.8, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.7, 2.6, 6.9, 2.3],
       [6.1, 2.9, 4.7, 1.4],
       [5. , 3.5, 1.3, 0.3],
       [5.9, 3

In [12]:
x_test

array([[4.9, 3. , 1.4, 0.2],
       [7.1, 3. , 5.9, 2.1],
       [6.7, 3.1, 4.4, 1.4],
       [6.1, 2.6, 5.6, 1.4],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.4, 1.5, 0.2],
       [6.7, 3.1, 4.7, 1.5],
       [7.9, 3.8, 6.4, 2. ],
       [6.5, 3. , 5.5, 1.8],
       [6. , 2.2, 5. , 1.5],
       [5.5, 4.2, 1.4, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.4, 3. , 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [5.8, 2.7, 4.1, 1. ],
       [4.3, 3. , 1.1, 0.1],
       [6.1, 3. , 4.9, 1.8],
       [5.7, 2.6, 3.5, 1. ],
       [6.4, 2.8, 5.6, 2.2],
       [5.6, 3. , 4.1, 1.3],
       [7.7, 3.8, 6.7, 2.2],
       [4.8, 3.4, 1.6, 0.2],
       [6.4, 3.1, 5.5, 1.8],
       [6.3, 2.9, 5.6, 1.8],
       [6.3, 3.3, 6. , 2.5],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2.3, 3.3, 1. ],
       [6.2, 2.9, 4.3, 1.3],
       [7.3, 2.9, 6.3, 1.8],
       [6.3, 2.7, 4.9, 1.8]])

In [13]:
y_train

array([1, 0, 2, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 2, 1, 1, 0, 2, 1, 0,
       0, 0, 2, 0, 0, 1, 0, 2, 2, 2, 1, 0, 1, 0, 2, 2, 1, 0, 2, 2, 0, 2,
       1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 0, 2, 0, 1, 1, 2, 1, 0, 1, 1, 1, 2,
       2, 2, 2, 0, 1, 0, 0, 0, 0, 0, 2, 1, 2, 0, 1, 1, 1, 2, 2, 1, 2, 1,
       1, 0, 0, 2, 0, 1, 1, 1, 1, 0, 1, 2, 1, 1, 2, 0, 2, 1, 0, 2, 1, 1,
       0, 0, 2, 2, 2, 1, 1, 0, 2, 1])

In [14]:
y_test

array([0, 2, 1, 2, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 1, 0, 2, 1, 2, 1, 2, 0,
       2, 2, 2, 0, 1, 1, 2, 2])

In [15]:
model=DecisionTreeClassifier()

In [16]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [18]:
y_pred=model.predict(x_test)
y_pred

array([0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 0, 0, 0, 0, 1, 0, 2, 1, 2, 1, 2, 0,
       2, 2, 2, 0, 1, 1, 2, 2])

In [19]:
ac=accuracy_score(y_test,y_pred)
ac

0.9333333333333333